### ISSUE TITLE
Score resets to zero when it gets to 100

### ISSUE THREAD

**Issue by ImSummerJohnson** [dylanhart/nerp#4]
Hi,
The score on this game resets to 0 when you reach 100, after the program says "Difficulty increased".
The name on the tab does indeed change to show that there is something happening, however the score is reset to zero.

Thanks!

**Comment by dylanhart** [comment]
This is intended behavior. Think of it as progressing to the next level. Not many people make it to 100 so not much time has been spent on this mechanic. I would be open to changing it.

**Comment by dylanhart** [comment]
Changing behavior. See #5.

**Comment by dylanhart** [comment]
Behavior has been changed.
